-- Seed: ancient Christianity study data.
-- Dates are zero-padded 4-digit year TEXT; BC prefixed with '-' (e.g., '-0006' = 6 BC).
-- Approximate dates use start_date/end_date as a range.

INSERT INTO location (name, historical_name, region, country) VALUES
  ('Jerusalem', 'Aelia Capitolina', 'Judea', 'Roman Empire'),
  ('Antioch', 'Antioch on the Orontes', 'Syria', 'Roman Empire'),
  ('Rome', NULL, 'Italia', 'Roman Empire'),
  ('Alexandria', NULL, 'Aegyptus', 'Roman Empire'),
  ('Carthage', NULL, 'Africa Proconsularis', 'Roman Empire'),
  ('Smyrna', NULL, 'Asia', 'Roman Empire'),
  ('Lugdunum', 'Lugdunum', 'Gallia Lugdunensis', 'Roman Empire'),
  ('Hippo Regius', NULL, 'Numidia', 'Roman Empire'),
  ('Constantinople', 'Byzantium', 'Thrace', 'Roman Empire'),
  ('Nicaea', NULL, 'Bithynia', 'Roman Empire'),
  ('Caesarea Maritima', NULL, 'Judea', 'Roman Empire'),
  ('Ephesus', NULL, 'Asia', 'Roman Empire'),
  ('Chalcedon', NULL, 'Bithynia', 'Roman Empire'),
  ('Bethlehem', NULL, 'Judea', 'Roman Empire');

INSERT INTO person (name, birth_date, death_date, nationality, occupation, biography) VALUES
  ('Jesus of Nazareth', '-0004', '0033', 'Judean', 'Rabbi, prophet', 'Central figure of Christianity; crucified under Pontius Pilate in Jerusalem.'),
  ('Paul of Tarsus', '0005', '0067', 'Roman citizen, Jewish', 'Apostle, tentmaker', 'Formerly Saul; convert who spread Christianity across the Mediterranean and authored much of the New Testament.'),
  ('Simon Peter', '0001', '0067', 'Galilean Jew', 'Fisherman, apostle', 'Chief among the Twelve; traditionally martyred in Rome under Nero.'),
  ('Ignatius of Antioch', '0035', '0108', 'Syrian', 'Bishop', 'Third bishop of Antioch; wrote seven letters en route to martyrdom in Rome.'),
  ('Polycarp of Smyrna', '0069', '0155', 'Greek', 'Bishop', 'Disciple of John the Apostle; bishop of Smyrna; burned at the stake.'),
  ('Justin Martyr', '0100', '0165', 'Samaritan Greek', 'Philosopher, apologist', 'Author of the First and Second Apologies and the Dialogue with Trypho; beheaded in Rome.'),
  ('Irenaeus of Lyon', '0130', '0202', 'Greek', 'Bishop, theologian', 'Bishop of Lugdunum; wrote Adversus Haereses against Gnosticism.'),
  ('Tertullian', '0155', '0220', 'Roman African', 'Theologian, jurist', 'First major Christian author to write in Latin; coined the term Trinitas.'),
  ('Origen', '0185', '0253', 'Egyptian Greek', 'Theologian, exegete', 'Prolific Alexandrian scholar; author of the Hexapla and De Principiis.'),
  ('Constantine I', '0272', '0337', 'Roman', 'Emperor', 'First Christian Roman emperor; legalized Christianity with the Edict of Milan; convened the Council of Nicaea.'),
  ('Eusebius of Caesarea', '0260', '0339', 'Roman Palestinian', 'Bishop, historian', 'Bishop of Caesarea; called the father of church history for his Ecclesiastical History.'),
  ('Athanasius of Alexandria', '0296', '0373', 'Egyptian', 'Bishop, theologian', 'Defender of Nicene orthodoxy against Arianism; exiled five times; wrote Life of Antony.'),
  ('Jerome', '0347', '0420', 'Roman Dalmatian', 'Priest, translator', 'Translated the Bible into Latin (the Vulgate); wrote De Viris Illustribus.'),
  ('Augustine of Hippo', '0354', '0430', 'Roman African', 'Bishop, theologian', 'Bishop of Hippo Regius; author of Confessions and City of God; shaped Western theology.'),
  ('Pontius Pilate', NULL, '0039', 'Roman', 'Prefect of Judea', 'Roman prefect who authorized the execution of Jesus.'),
  ('Nero', '0037', '0068', 'Roman', 'Emperor', 'Roman emperor during the first major persecution of Christians in Rome.'),
  ('Decius', '0201', '0251', 'Roman', 'Emperor', 'Emperor who issued the first empire-wide edict requiring sacrifice to Roman gods.'),
  ('Cyril of Alexandria', '0376', '0444', 'Egyptian', 'Patriarch, theologian', 'Patriarch of Alexandria; leading figure at the Council of Ephesus.');

INSERT INTO event (title, description, start_date, end_date, location_id) VALUES
  ('Crucifixion of Jesus', 'Jesus of Nazareth is crucified under Pontius Pilate in Jerusalem. Christians regard this death and the reported resurrection three days later as the founding events of the faith.', '0030', '0033', (SELECT id FROM location WHERE name = 'Jerusalem')),
  ('Pentecost', 'Fifty days after Passover, Jesus'' followers in Jerusalem experience what the Book of Acts describes as the descent of the Holy Spirit, beginning the public preaching of the apostles.', '0033', NULL, (SELECT id FROM location WHERE name = 'Jerusalem')),
  ('Conversion of Paul', 'Saul of Tarsus, a Pharisee persecuting the early church, converts on the road to Damascus and becomes the apostle Paul.', '0034', '0036', NULL),
  ('Council of Jerusalem', 'The apostles and elders in Jerusalem decide that Gentile converts need not be circumcised or fully observe the Mosaic Law, clearing the path for Christianity''s spread beyond Judaism.', '0049', '0050', (SELECT id FROM location WHERE name = 'Jerusalem')),
  ('Neronian Persecution', 'After the Great Fire of Rome, Nero blames Christians and inaugurates the first state persecution. Tradition places the martyrdoms of Peter and Paul in this period.', '0064', '0067', (SELECT id FROM location WHERE name = 'Rome')),
  ('Destruction of the Second Temple', 'Roman forces under Titus destroy the Jerusalem Temple during the First Jewish–Roman War, a pivotal event for both Judaism and nascent Christianity.', '0070', NULL, (SELECT id FROM location WHERE name = 'Jerusalem')),
  ('Martyrdom of Ignatius', 'Ignatius, bishop of Antioch, is transported to Rome and killed in the arena. His seven letters along the way are among the earliest post-apostolic writings.', '0108', '0110', (SELECT id FROM location WHERE name = 'Rome')),
  ('Martyrdom of Polycarp', 'Polycarp of Smyrna, disciple of John the Apostle, is burned at the stake after refusing to recant. The Martyrdom of Polycarp is among the oldest surviving martyr acts.', '0155', '0156', (SELECT id FROM location WHERE name = 'Smyrna')),
  ('Martyrdom of Justin', 'Justin Martyr and several companions are beheaded in Rome under the prefect Rusticus, after Justin refuses to sacrifice to the Roman gods.', '0165', NULL, (SELECT id FROM location WHERE name = 'Rome')),
  ('Against Heresies', 'Irenaeus of Lyon completes Adversus Haereses, a systematic refutation of Gnostic sects and an early articulation of apostolic tradition and the rule of faith.', '0180', '0185', (SELECT id FROM location WHERE name = 'Lugdunum')),
  ('Decian Persecution', 'The emperor Decius issues an edict requiring all inhabitants to sacrifice to the Roman gods and obtain a libellus. Refusers, many of them Christians, are punished.', '0250', '0251', (SELECT id FROM location WHERE name = 'Rome')),
  ('Edict of Milan', 'Constantine and Licinius grant religious toleration throughout the empire, ending official persecution of Christians and returning confiscated property.', '0313', NULL, (SELECT id FROM location WHERE name = 'Rome')),
  ('Council of Nicaea', 'The first ecumenical council, convened by Constantine, addresses Arianism and produces the original Nicene Creed affirming the Son is consubstantial with the Father.', '0325', NULL, (SELECT id FROM location WHERE name = 'Nicaea')),
  ('Death of Constantine', 'Constantine I dies at Nicomedia after being baptized on his deathbed by Eusebius of Nicomedia.', '0337', NULL, NULL),
  ('Exiles of Athanasius', 'Athanasius of Alexandria is exiled five times over decades as the Arian controversy ebbs and flows under successive emperors.', '0335', '0366', (SELECT id FROM location WHERE name = 'Alexandria')),
  ('Council of Constantinople', 'The second ecumenical council reaffirms and expands the Nicene Creed and affirms the full divinity of the Holy Spirit.', '0381', NULL, (SELECT id FROM location WHERE name = 'Constantinople')),
  ('Conversion of Augustine', 'Augustine of Hippo is baptized by Ambrose in Milan after his conversion in a Milanese garden, an episode later recounted in the Confessions.', '0386', '0387', (SELECT id FROM location WHERE name = 'Rome')),
  ('Jerome''s Vulgate', 'Jerome, at the request of Pope Damasus, produces a Latin translation of the Bible from Hebrew and Greek sources that becomes the standard Western text for over a millennium.', '0382', '0405', (SELECT id FROM location WHERE name = 'Bethlehem')),
  ('City of God', 'Augustine writes De Civitate Dei after the sack of Rome in 410, defending Christianity against pagan accusations and contrasting the earthly and heavenly cities.', '0413', '0426', (SELECT id FROM location WHERE name = 'Hippo Regius')),
  ('Council of Ephesus', 'The third ecumenical council condemns Nestorianism and affirms the title Theotokos (God-bearer) for Mary.', '0431', NULL, (SELECT id FROM location WHERE name = 'Ephesus')),
  ('Council of Chalcedon', 'The fourth ecumenical council defines the two natures of Christ, human and divine, united in one person without confusion or division.', '0451', NULL, (SELECT id FROM location WHERE name = 'Chalcedon'));

INSERT INTO source (title, author, publication_date, url, citation, source_type) VALUES
  ('Gospel of Matthew', 'Unknown (attributed to Matthew the Apostle)', '0080', NULL, 'The Gospel According to Matthew. In The Holy Bible: New Revised Standard Version. National Council of Churches, 1989.', 'PRIMARY'),
  ('Acts of the Apostles', 'Luke the Evangelist (attributed)', '0085', NULL, 'The Acts of the Apostles. In The Holy Bible: New Revised Standard Version. National Council of Churches, 1989.', 'PRIMARY'),
  ('Pauline Epistles', 'Paul of Tarsus', '0060', NULL, 'The Letters of Paul. In The Holy Bible: New Revised Standard Version. National Council of Churches, 1989.', 'PRIMARY'),
  ('Letters of Ignatius', 'Ignatius of Antioch', '0110', NULL, 'Ignatius of Antioch. The Apostolic Fathers, Volume I. Translated by Bart D. Ehrman, Loeb Classical Library 24, Harvard University Press, 2003.', 'PRIMARY'),
  ('Martyrdom of Polycarp', 'Unknown (church at Smyrna)', '0160', NULL, 'The Martyrdom of Polycarp. In The Apostolic Fathers, Volume I, translated by Bart D. Ehrman, Loeb Classical Library 24, Harvard University Press, 2003.', 'PRIMARY'),
  ('Against Heresies', 'Irenaeus of Lyon', '0185', NULL, 'Irenaeus of Lyon. Against Heresies. Translated by Dominic J. Unger, Ancient Christian Writers 55, Paulist Press, 1992.', 'PRIMARY'),
  ('Ecclesiastical History', 'Eusebius of Caesarea', '0325', NULL, 'Eusebius of Caesarea. The Ecclesiastical History, Volumes I–II. Translated by Kirsopp Lake, Loeb Classical Library 153 and 265, Harvard University Press, 1926–1932.', 'PRIMARY'),
  ('Life of Antony', 'Athanasius of Alexandria', '0360', NULL, 'Athanasius. The Life of Antony and the Letter to Marcellinus. Translated by Robert C. Gregg, Classics of Western Spirituality, Paulist Press, 1980.', 'PRIMARY'),
  ('De Viris Illustribus', 'Jerome', '0393', NULL, 'Jerome. On Illustrious Men. Translated by Thomas P. Halton, Fathers of the Church 100, Catholic University of America Press, 1999.', 'PRIMARY'),
  ('Confessions', 'Augustine of Hippo', '0400', NULL, 'Augustine. Confessions. Translated by Henry Chadwick, Oxford World''s Classics, Oxford University Press, 1991.', 'PRIMARY'),
  ('City of God', 'Augustine of Hippo', '0426', NULL, 'Augustine. The City of God against the Pagans. Translated by R. W. Dyson, Cambridge Texts in the History of Political Thought, Cambridge University Press, 1998.', 'PRIMARY');

-- person_to_event: who participated in what
INSERT INTO person_to_event (person_id, event_id, role) VALUES
  ((SELECT id FROM person WHERE name = 'Jesus of Nazareth'),      (SELECT id FROM event WHERE title = 'Crucifixion of Jesus'),           'Crucified'),
  ((SELECT id FROM person WHERE name = 'Pontius Pilate'),          (SELECT id FROM event WHERE title = 'Crucifixion of Jesus'),           'Roman prefect'),
  ((SELECT id FROM person WHERE name = 'Simon Peter'),             (SELECT id FROM event WHERE title = 'Pentecost'),                      'Apostle, preached'),
  ((SELECT id FROM person WHERE name = 'Paul of Tarsus'),          (SELECT id FROM event WHERE title = 'Conversion of Paul'),             'Converted'),
  ((SELECT id FROM person WHERE name = 'Paul of Tarsus'),          (SELECT id FROM event WHERE title = 'Council of Jerusalem'),           'Delegate from Antioch'),
  ((SELECT id FROM person WHERE name = 'Simon Peter'),             (SELECT id FROM event WHERE title = 'Council of Jerusalem'),           'Apostle'),
  ((SELECT id FROM person WHERE name = 'Paul of Tarsus'),          (SELECT id FROM event WHERE title = 'Neronian Persecution'),           'Martyred'),
  ((SELECT id FROM person WHERE name = 'Simon Peter'),             (SELECT id FROM event WHERE title = 'Neronian Persecution'),           'Martyred'),
  ((SELECT id FROM person WHERE name = 'Nero'),                    (SELECT id FROM event WHERE title = 'Neronian Persecution'),           'Instigator'),
  ((SELECT id FROM person WHERE name = 'Ignatius of Antioch'),     (SELECT id FROM event WHERE title = 'Martyrdom of Ignatius'),          'Martyr'),
  ((SELECT id FROM person WHERE name = 'Polycarp of Smyrna'),      (SELECT id FROM event WHERE title = 'Martyrdom of Polycarp'),          'Martyr'),
  ((SELECT id FROM person WHERE name = 'Justin Martyr'),           (SELECT id FROM event WHERE title = 'Martyrdom of Justin'),            'Martyr'),
  ((SELECT id FROM person WHERE name = 'Irenaeus of Lyon'),        (SELECT id FROM event WHERE title = 'Against Heresies'),               'Author'),
  ((SELECT id FROM person WHERE name = 'Decius'),                  (SELECT id FROM event WHERE title = 'Decian Persecution'),             'Emperor'),
  ((SELECT id FROM person WHERE name = 'Origen'),                  (SELECT id FROM event WHERE title = 'Decian Persecution'),             'Imprisoned and tortured'),
  ((SELECT id FROM person WHERE name = 'Constantine I'),           (SELECT id FROM event WHERE title = 'Edict of Milan'),                 'Issuer'),
  ((SELECT id FROM person WHERE name = 'Constantine I'),           (SELECT id FROM event WHERE title = 'Council of Nicaea'),              'Convener'),
  ((SELECT id FROM person WHERE name = 'Athanasius of Alexandria'),(SELECT id FROM event WHERE title = 'Council of Nicaea'),              'Deacon, secretary to Alexander'),
  ((SELECT id FROM person WHERE name = 'Eusebius of Caesarea'),    (SELECT id FROM event WHERE title = 'Council of Nicaea'),              'Attendee and historian'),
  ((SELECT id FROM person WHERE name = 'Constantine I'),           (SELECT id FROM event WHERE title = 'Death of Constantine'),           'Subject'),
  ((SELECT id FROM person WHERE name = 'Eusebius of Caesarea'),    (SELECT id FROM event WHERE title = 'Death of Constantine'),           'Biographer'),
  ((SELECT id FROM person WHERE name = 'Athanasius of Alexandria'),(SELECT id FROM event WHERE title = 'Exiles of Athanasius'),           'Subject'),
  ((SELECT id FROM person WHERE name = 'Athanasius of Alexandria'),(SELECT id FROM event WHERE title = 'Council of Constantinople'),      'Posthumous influence'),
  ((SELECT id FROM person WHERE name = 'Augustine of Hippo'),      (SELECT id FROM event WHERE title = 'Conversion of Augustine'),        'Convert'),
  ((SELECT id FROM person WHERE name = 'Jerome'),                  (SELECT id FROM event WHERE title = 'Jerome''s Vulgate'),              'Translator'),
  ((SELECT id FROM person WHERE name = 'Augustine of Hippo'),      (SELECT id FROM event WHERE title = 'City of God'),                    'Author'),
  ((SELECT id FROM person WHERE name = 'Cyril of Alexandria'),     (SELECT id FROM event WHERE title = 'Council of Ephesus'),             'Presiding bishop'),
  ((SELECT id FROM person WHERE name = 'Cyril of Alexandria'),     (SELECT id FROM event WHERE title = 'Council of Chalcedon'),           'Posthumous authority');

-- source_to_event: which sources document which events
INSERT INTO source_to_event (source_id, event_id) VALUES
  ((SELECT id FROM source WHERE title = 'Gospel of Matthew'),        (SELECT id FROM event WHERE title = 'Crucifixion of Jesus')),
  ((SELECT id FROM source WHERE title = 'Acts of the Apostles'),     (SELECT id FROM event WHERE title = 'Pentecost')),
  ((SELECT id FROM source WHERE title = 'Acts of the Apostles'),     (SELECT id FROM event WHERE title = 'Conversion of Paul')),
  ((SELECT id FROM source WHERE title = 'Acts of the Apostles'),     (SELECT id FROM event WHERE title = 'Council of Jerusalem')),
  ((SELECT id FROM source WHERE title = 'Pauline Epistles'),         (SELECT id FROM event WHERE title = 'Council of Jerusalem')),
  ((SELECT id FROM source WHERE title = 'Ecclesiastical History'),   (SELECT id FROM event WHERE title = 'Neronian Persecution')),
  ((SELECT id FROM source WHERE title = 'Ecclesiastical History'),   (SELECT id FROM event WHERE title = 'Destruction of the Second Temple')),
  ((SELECT id FROM source WHERE title = 'Letters of Ignatius'),      (SELECT id FROM event WHERE title = 'Martyrdom of Ignatius')),
  ((SELECT id FROM source WHERE title = 'Martyrdom of Polycarp'),    (SELECT id FROM event WHERE title = 'Martyrdom of Polycarp')),
  ((SELECT id FROM source WHERE title = 'Ecclesiastical History'),   (SELECT id FROM event WHERE title = 'Martyrdom of Justin')),
  ((SELECT id FROM source WHERE title = 'Against Heresies'),         (SELECT id FROM event WHERE title = 'Against Heresies')),
  ((SELECT id FROM source WHERE title = 'Ecclesiastical History'),   (SELECT id FROM event WHERE title = 'Decian Persecution')),
  ((SELECT id FROM source WHERE title = 'Ecclesiastical History'),   (SELECT id FROM event WHERE title = 'Edict of Milan')),
  ((SELECT id FROM source WHERE title = 'Ecclesiastical History'),   (SELECT id FROM event WHERE title = 'Council of Nicaea')),
  ((SELECT id FROM source WHERE title = 'Ecclesiastical History'),   (SELECT id FROM event WHERE title = 'Death of Constantine')),
  ((SELECT id FROM source WHERE title = 'Life of Antony'),           (SELECT id FROM event WHERE title = 'Exiles of Athanasius')),
  ((SELECT id FROM source WHERE title = 'Confessions'),              (SELECT id FROM event WHERE title = 'Conversion of Augustine')),
  ((SELECT id FROM source WHERE title = 'De Viris Illustribus'),     (SELECT id FROM event WHERE title = 'Jerome''s Vulgate')),
  ((SELECT id FROM source WHERE title = 'City of God'),              (SELECT id FROM event WHERE title = 'City of God'));
